<?php

return [
    'definitions' => [
        ['value' => 'Appetizers', 'arabic' => 'مقبلات'],
        ['value' => 'Salads', 'arabic' => 'سلطات'],
        ['value' => 'Soups', 'arabic' => 'شوربات'],
        ['value' => 'Main Courses', 'arabic' => 'الأطباق الرئيسية'],
        ['value' => 'Sides', 'arabic' => 'أطباق جانبية'],
        ['value' => 'Desserts', 'arabic' => 'حلويات'],
        ['value' => 'Drinks', 'arabic' => 'مشروبات'],
        ['value' => 'Pizza', 'arabic' => 'بيتزا'],
        ['value' => 'Specialty Pizza', 'arabic' => 'بيتزا خاصة'],
        ['value' => 'Burgers', 'arabic' => 'برغر'],
        ['value' => 'Sandwiches', 'arabic' => 'ساندويتشات'],
        ['value' => 'Wraps', 'arabic' => 'راب'],
        ['value' => 'Hot Dogs', 'arabic' => 'هوت دوغ'],
        ['value' => 'Pasta', 'arabic' => 'باستا'],
        ['value' => 'Rice Dishes', 'arabic' => 'أطباق الأرز'],
        ['value' => 'Noodles', 'arabic' => 'نودلز'],
        ['value' => 'Chicken', 'arabic' => 'دجاج'],
        ['value' => 'Beef', 'arabic' => 'لحم بقري'],
        ['value' => 'Lamb', 'arabic' => 'لحم غنم'],
        ['value' => 'Seafood', 'arabic' => 'مأكولات بحرية'],
        ['value' => 'Vegetarian', 'arabic' => 'نباتي'],
        ['value' => 'Vegan', 'arabic' => 'نباتي صرف'],
        ['value' => 'Cold Mezze', 'arabic' => 'مقبلات باردة'],
        ['value' => 'Hot Mezze', 'arabic' => 'مقبلات ساخنة'],
        ['value' => 'Grills', 'arabic' => 'مشاوي'],
        ['value' => 'Shawarma', 'arabic' => 'شاورما'],
        ['value' => 'Manakish', 'arabic' => 'مناقيش'],
        ['value' => 'Traditional Dishes', 'arabic' => 'أكلات تقليدية'],
        ['value' => 'Italian', 'arabic' => 'إيطالي'],
        ['value' => 'American', 'arabic' => 'أمريكي'],
        ['value' => 'Mexican', 'arabic' => 'مكسيكي'],
        ['value' => 'Indian', 'arabic' => 'هندي'],
        ['value' => 'Chinese', 'arabic' => 'صيني'],
        ['value' => 'Japanese', 'arabic' => 'ياباني'],
        ['value' => 'Thai', 'arabic' => 'تايلندي'],
        ['value' => 'Korean', 'arabic' => 'كوري'],
        ['value' => 'Mediterranean', 'arabic' => 'متوسطي'],
        ['value' => 'Turkish', 'arabic' => 'تركي'],
        ['value' => 'Breakfast', 'arabic' => 'فطور'],
        ['value' => 'Brunch', 'arabic' => 'فطور متأخر'],
        ['value' => 'Lunch', 'arabic' => 'غداء'],
        ['value' => 'Dinner', 'arabic' => 'عشاء'],
        ['value' => 'Hot Drinks', 'arabic' => 'مشروبات ساخنة'],
        ['value' => 'Cold Drinks', 'arabic' => 'مشروبات باردة'],
        ['value' => 'Coffee', 'arabic' => 'قهوة'],
        ['value' => 'Tea', 'arabic' => 'شاي'],
        ['value' => 'Fresh Juices', 'arabic' => 'عصائر طازجة'],
        ['value' => 'Smoothies', 'arabic' => 'سموذي'],
        ['value' => 'Milkshakes', 'arabic' => 'ميلك شيك'],
        ['value' => 'Soft Drinks', 'arabic' => 'مشروبات غازية'],
        ['value' => 'Mocktails', 'arabic' => 'موكتيل'],
        ['value' => 'Cakes', 'arabic' => 'كيك'],
        ['value' => 'Pastries', 'arabic' => 'معجنات'],
        ['value' => 'Ice Cream', 'arabic' => 'آيس كريم'],
        ['value' => 'Arabic Sweets', 'arabic' => 'حلويات عربية'],
        ['value' => 'Bakery', 'arabic' => 'مخبوزات'],
        ['value' => 'Chef Specials', 'arabic' => 'أطباق الشيف'],
        ['value' => 'Popular Items', 'arabic' => 'الأكثر طلبًا'],
        ['value' => 'New Items', 'arabic' => 'جديد'],
        ['value' => 'Signature Dishes', 'arabic' => 'أطباق مميزة'],
        ['value' => 'Combo Meals', 'arabic' => 'وجبات كومبو'],
        ['value' => 'Kids Menu', 'arabic' => 'قائمة الأطفال'],
        ['value' => 'Healthy Options', 'arabic' => 'خيارات صحية'],
        ['value' => 'Gluten Free', 'arabic' => 'خالٍ من الغلوتين'],
        ['value' => 'Low Carb', 'arabic' => 'منخفض الكربوهيدرات'],
        ['value' => 'Spicy', 'arabic' => 'حار'],
        ['value' => 'Buffet', 'arabic' => 'بوفيه'],
        ['value' => 'Live Cooking', 'arabic' => 'طبخ مباشر'],
        ['value' => 'Salad Bar', 'arabic' => 'بار سلطات'],
        ['value' => 'Dessert Station', 'arabic' => 'ركن الحلويات'],
    ],
    'values' => [
        'Appetizers',
        'Salads',
        'Soups',
        'Main Courses',
        'Sides',
        'Desserts',
        'Drinks',
        'Pizza',
        'Specialty Pizza',
        'Burgers',
        'Sandwiches',
        'Wraps',
        'Hot Dogs',
        'Pasta',
        'Rice Dishes',
        'Noodles',
        'Chicken',
        'Beef',
        'Lamb',
        'Seafood',
        'Vegetarian',
        'Vegan',
        'Cold Mezze',
        'Hot Mezze',
        'Grills',
        'Shawarma',
        'Manakish',
        'Traditional Dishes',
        'Italian',
        'American',
        'Mexican',
        'Indian',
        'Chinese',
        'Japanese',
        'Thai',
        'Korean',
        'Mediterranean',
        'Turkish',
        'Breakfast',
        'Brunch',
        'Lunch',
        'Dinner',
        'Hot Drinks',
        'Cold Drinks',
        'Coffee',
        'Tea',
        'Fresh Juices',
        'Smoothies',
        'Milkshakes',
        'Soft Drinks',
        'Mocktails',
        'Cakes',
        'Pastries',
        'Ice Cream',
        'Arabic Sweets',
        'Bakery',
        'Chef Specials',
        'Popular Items',
        'New Items',
        'Signature Dishes',
        'Combo Meals',
        'Kids Menu',
        'Healthy Options',
        'Gluten Free',
        'Low Carb',
        'Spicy',
        'Buffet',
        'Live Cooking',
        'Salad Bar',
        'Dessert Station',
    ],
];
